name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Paso: Calcular versión semántica
    - name: Calculate semantic version
      id: version
      uses: PaulHatch/semantic-version@v4
      with:
        tag_prefix: "v"
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |        
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build docker image
      run: |
        docker build -t fabrizio1306/docker-graphql:${{ steps.version.outputs.version }} .

    - name: Push docker image (versioned)
      run: |
        docker push fabrizio1306/docker-graphql:${{ steps.version.outputs.version }}

    - name: Tag image as latest
      run: |
        docker tag fabrizio1306/docker-graphql:${{ steps.version.outputs.version }} fabrizio1306/docker-graphql:latest

    - name: Push docker image (latest)
      run: |
        docker push fabrizio1306/docker-graphql:latest
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
