name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # Paso: Calcular versi칩n sem치ntica
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}"
      id: version

    - name: Show generated semantic version
      run: |
        echo "La versi칩n generada autom치ticamente es: ${{ steps.version.outputs.version }}" 
    
    # - name: Docker login
    #   env:
    #     DOCKER_USER: ${{ secrets.DOCKER_USER }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   run: |        
    #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    # - name: Build docker image
    #   env:
    #     NEW_VERSION: ${{ steps.version.outputs.version }}
    #   run: |
    #     docker build -t fabrizio1306/docker-graphql:$NEW_VERSION .
    #     docker tag fabrizio1306/docker-graphql:$NEW_VERSION fabrizio1306/docker-graphql:latest
    
    # - name: Push docker image (versioned)
    #   env:
    #     NEW_VERSION: ${{ steps.version.outputs.version }}
    #   run: |
    #     docker push fabrizio1306/docker-graphql:$NEW_VERSION
    #     docker push fabrizio1306/docker-graphql:latest
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
